-----(((NUMPY INTRODUCTION)))--------

--->numpy is an standard python library
--->numpy is an open source library
--->numpy is used for mathematical opeartions, scientific computations, data analysis and etc.

In [4]:
import numpy as np
a=np.array([12,23,45])
print(a)
b=np.arange(10)
print(b)

[12 23 45]
[0 1 2 3 4 5 6 7 8 9]


->when compared to lists, arrays are fast to compute.
->there is no need for fo loop.

In [11]:
b=range(1000)
%timeit [i**2 for i in b]

47.3 μs ± 1.32 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
b=np.arange(10)
%timeit b**2

642 ns ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


creation of one dimensional array


In [20]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4]
1
(4,)


creation of two dimensional array

In [19]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]]
2
(2, 2)


creation of three dimensional array

In [18]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


functions for creating array

In [21]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [23]:
#here linspace mean from starting point to ending point it divide them in some parts as mentioned in the argument.
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [25]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
#In diagonally we will get ones
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
print(np.diag(a))

[1 2 3 4]


BASIC DATA TYPES

In [31]:
a=np.arange(10)
print(a.dtype)

int64


In [32]:
a=np.arange(10,dtype="float64")
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


OTHER DATATYPE

In [33]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [35]:
a=np.array([True,False])
print(a)
print(a.dtype)

[ True False]
bool


In [38]:
a=np.array(["jasmin","shaik"])
print(a)
print(a.dtype)
#u means unicode string type and 6 means highest length

['jasmin' 'shaik']
<U6


INDEXING AND SLICING

In [40]:
a=np.arange(10)
print(a[5])
#prints 5th element

5


In [41]:
a=np.arange(2,20,2)
print(a[2])

6


In [42]:
a=np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [43]:
a[1,2]=3
print(a)

[[1 0 0]
 [0 2 3]
 [0 0 3]]


SLICING

In [44]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(a[1:8:2])

[1 3 5 7]


COPIES AND VIEWING

In [2]:
import numpy as np
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [35]:
#points to the same memory location 
print(np.shares_memory(a,b))

False


In [10]:
b[0]=8
#this is called viewing here both variables share memory so change in one can also change in another
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[8 2 4 6 8]


In [7]:
a=np.arange(10)
#forces to create another copy
b=a[::2].copy()
print(a)
print(b)
print(np.shares_memory(a,b))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
False


In [14]:
b[0]=8
#here we separate memories so the value will not effect other
print(a)
print(b)


[1 2 6 1 2]
[8 2 4 6 8]


RANDOM NUMBER GENERATOR

In [13]:
#random is a module and randint is a function in it .
# if we want we can import random and can use it.
a=np.random.randint(0,9,5)
print(a)

[1 2 6 1 2]


ELEMENT WISE OPEARTIONS

In [16]:
a=np.array([1,2,3,4])
print(a+1)  

[2 3 4 5]


In [17]:
print(a**2)

[ 1  4  9 16]


all arithmetic opeartors elementwise

In [18]:
b=np.ones(4)+1
print(a)
print(b)

[1 2 3 4]
[2. 2. 2. 2.]


In [19]:
print(a*b)

[2. 4. 6. 8.]


comparision opeartors

In [23]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
#element wise comparision
print(a==b)
print(a<b)
print(a>b)

[False False False False]
[ True  True  True  True]
[False False False False]


In [24]:
#array wise comparision
print(np.array_equal(a,b))

False


LOGICAL OPERATORS

In [27]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,0,0,1],dtype="bool")
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True False  True  True]
[ True False False False]


TRIGNOMETRY

In [28]:
a=np.array([1,2,3,4])
print(a)
print(np.sin(a))

[1 2 3 4]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [29]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436]


In [30]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


BASIC REDUCTIONS

In [31]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [33]:
x=np.array([[1,2],[3,4]])
print(x)
#coloumn wise sum
x.sum(axis=0)

[[1 2]
 [3 4]]


array([4, 6])

In [43]:
#row wise sum
x=np.array([[1,2],[3,4]])
x.sum(axis=1)

array([3, 7])

other reductins

In [38]:
x=np.array([1,2,3,4])
print(x.max())
print(x.min())
#argmin returns the index of the smallest one.
print(x.argmin())
print(x.argmax())

4
1
0
3
