-----(((NUMPY INTRODUCTION)))--------

--->numpy is an standard python library
--->numpy is an open source library
--->numpy is used for mathematical opeartions, scientific computations, data analysis and etc.

In [4]:
import numpy as np
a=np.array([12,23,45])
print(a)
b=np.arange(10)
print(b)

[12 23 45]
[0 1 2 3 4 5 6 7 8 9]


->when compared to lists, arrays are fast to compute.
->there is no need for fo loop.

In [11]:
b=range(1000)
%timeit [i**2 for i in b]

47.3 μs ± 1.32 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
b=np.arange(10)
%timeit b**2

642 ns ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


creation of one dimensional array


In [20]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4]
1
(4,)


creation of two dimensional array

In [19]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]]
2
(2, 2)


creation of three dimensional array

In [18]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


functions for creating array

In [21]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [23]:
#here linspace mean from starting point to ending point it divide them in some parts as mentioned in the argument.
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [25]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
#In diagonally we will get ones
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
print(np.diag(a))

[1 2 3 4]


BASIC DATA TYPES

In [31]:
a=np.arange(10)
print(a.dtype)

int64


In [32]:
a=np.arange(10,dtype="float64")
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


OTHER DATATYPE

In [33]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [35]:
a=np.array([True,False])
print(a)
print(a.dtype)

[ True False]
bool


In [38]:
a=np.array(["jasmin","shaik"])
print(a)
print(a.dtype)
#u means unicode string type and 6 means highest length

['jasmin' 'shaik']
<U6


INDEXING AND SLICING

In [40]:
a=np.arange(10)
print(a[5])
#prints 5th element

5


In [41]:
a=np.arange(2,20,2)
print(a[2])

6


In [42]:
a=np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [43]:
a[1,2]=3
print(a)

[[1 0 0]
 [0 2 3]
 [0 0 3]]


SLICING

In [44]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(a[1:8:2])

[1 3 5 7]
